# Name of the workflow
name: python CI/CD

  # Controls when the workflow will run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows to run this workflow manually from Actions tab
workflow_dispatch:

  jobs:
    ci:
      runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v2 

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9


      - name: Run Tests
        run: |
          python3 -m unittest test_utils

